### ISSUE TITLE
Entity values are "Unknown"

### ISSUE THREAD

**Issue by axyaxyfr** [rcasula/kostalpiko-homeassistant#16]
I'm unsure what to put in my kostal.yaml...
I currently have:

host: 192.168.1.165
username: pvserver
password: pvwr
monitored_conditions:

    current_power
    total_energy
    daily_energy
    string1_voltage
    string1_current
    string2_voltage
    string2_current
    l1_voltage
    l1_power
    status

I'll attach a screenshot. It can see that it's a piko 3.6 so something must be right...

![kostal3](https://user-images.githubusercontent.com/98274455/186008751-e26eae74-b5bc-4593-ad23-6cb926095702.png)

Why are the values unknown?

**Comment by tvanoirschot** [comment]
exactly the same over here, even on a clean install 
Home Assistant 2022.8.6 Supervisor 2022.08.3 Operating System 8.5

**Comment by rcasula** [comment]
Hi, can I have the complete config file?

in the meantime you can try this example config file:
```
kostal:
  host: XXX.XXX.XXX.XXX
  username: xxxxx
  password: xxxxx
  monitored_conditions:
    - current_power
    - total_energy
    - daily_energy
    - status
```
