### ISSUE TITLE
Example configuration

### ISSUE THREAD

**Issue by tunguskar** [rcasula/kostalpiko-homeassistant#3]
Hi there,

Is it possible that you send me an example configuration for your module? 

Kind Regards

**Comment by rcasula** [comment]
Hi, you can use Config Flow or the following example:
```
kostal:
  host: XXX.XXX.XXX.XXX
  username: xxxxx
  password: xxxxx
  monitored_conditions:
    - current_power
    - total_energy
    - daily_energy
    - status
```
